name: Gradle CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: gradle/actions/setup-gradle@v4
      - name: Configure Git User Details
        run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"

      - name: Apply Patches
        run: ./gradlew applyAllPatches --stacktrace
      - name: Build
        run: ./gradlew build

      - name: Create Paperclip Jar
        if: github.event_name == 'push'
        run: ./gradlew createMojmapPaperclipJar --stacktrace
      - uses: actions/upload-artifact@v4
        if: github.event_name == 'push'
        with:
          name: Fork
          path: fork/build/libs/fork-paperclip-*-mojmap.jar
